### ISSUE TITLE
Producer and Creator values

### ISSUE THREAD

**Issue by d-ruiz** [pmassing/auler.gmbh.zugferdxinvoice#16]
Hi @pmassing, 

One more thing we noticed is that the process is setting the producer and creator values with values that might be improved. 

Producer = Client name
Creator = invoice user name

In the [mustang documentation](https://www.mustangproject.org/invoice-class/). I see that they set the Producer to the application name and creator to the user creating the invoice. 

```
            IZUGFeRDExporter ze = new ZUGFeRDExporterFromPDFA().load(sourcePDF).setProducer("My Application").
                    setCreator(System.getProperty("user.name"));
```

The producer name might be ok with the client name or perhaps it can be iDempiere or the name of the specific distro but the creator name should be the user creating the invoice (CreatedBy) or the sales rep. 

What do you think?

**Comment by pmassing** [comment]
Hi @d-ruiz ,

yes, accepted
